import { keccak256, stringToBytes } from "viem";

export type DAO = {
  name: string;
  iconURL: string;
  expectedDomain: string;
  emailDomain: string;
  token: string;
  domainHash: string;
  tokenAddress: string;
};

export const DAO_MAPPING: DAO[] = [
  {
    name: "MakerDAO",
    iconURL: "https://cryptologos.cc/logos/maker-mkr-logo.png?v=025",
    token: "MKR",
    tokenAddress:"0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2",
    emailDomain: "makerdao.com",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Compound DAO",
    iconURL: "https://cryptologos.cc/logos/compound-comp-logo.png?v=025",
    token: "COMP",
    tokenAddress: "0xc00e94cb662c3520282e6f5717214004a7f26888",
    emailDomain: "compound.finance",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Uniswap DAO",
    iconURL: "https://cryptologos.cc/logos/uniswap-uni-logo.png?v=025",
    token: "UNI",
    tokenAddress:"0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
    emailDomain: "uniswap.org",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Aave DAO",
    iconURL: "https://cryptologos.cc/logos/aave-aave-logo.png?v=025",
    token: "AAVE",
    tokenAddress:"0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
    emailDomain: "aave.com",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Curve DAO",
    iconURL: "https://cryptologos.cc/logos/curve-dao-crv-logo.png?v=025",
    token: "CRV",
    tokenAddress:"0x0994206dfe8de6ec6920ff4d779b0d950605fb53",
    emailDomain: "curve.fi",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "SushiSwap DAO",
    iconURL: "https://cryptologos.cc/logos/sushi-sushi-logo.png?v=025",
    token: "SUSHI",
    tokenAddress:"0x6b3595068778dd592e39a122f4f5a5cf09c90fe2",
    emailDomain: "sushi.com",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Yearn Finance DAO",
    iconURL: "https://cryptologos.cc/logos/yearn-finance-yfi-logo.png?v=025",
    token: "YFI",
    tokenAddress:"0x0bc529c00C6401aEF6D220BE8C6Ea1667F6Ad93e",
    emailDomain: "yearn.finance",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Aragon DAO",
    iconURL: "https://cryptologos.cc/logos/aragon-ant-logo.png?v=025",
    token: "ANT",
    emailDomain: "aragon.org",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Balancer DAO",
    iconURL: "https://cryptologos.cc/logos/balancer-bal-logo.png?v=025",
    token: "BAL",
    tokenAddress:"0xba100000625a3754423978a60c9317c58a424e3d",
    emailDomain: "balancer.fi",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Synthetix DAO",
    iconURL: "https://cryptologos.cc/logos/synthetix-snx-logo.png?v=025",
    token: "SNX",
    emailDomain: "synthetix.io",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Gitcoin DAO",
    iconURL: "https://cryptologos.cc/logos/gitcoin-gtc-logo.png?v=025",
    token: "GTC",
    tokenAddress:"0xDe30da39c46104798bB5aA3fe8B9e0e1F348163F",
    emailDomain: "gitcoin.co",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "ENS DAO",
    iconURL:
      "https://cryptologos.cc/logos/ethereum-name-service-ens-logo.png?v=025",
    token: "ENS",
    tokenAddress:"0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72",
    emailDomain: "ens.domains",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Lido DAO",
    iconURL: "https://cryptologos.cc/logos/lido-dao-ldo-logo.png?v=025",
    token: "LDO",
    emailDomain: "lido.fi",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Frax Finance DAO",
    iconURL: "https://cryptologos.cc/logos/frax-finance-fxs-logo.png?v=025",
    token: "FXS",
    emailDomain: "frax.finance",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "The Graph DAO",
    iconURL: "https://cryptologos.cc/logos/the-graph-grt-logo.png?v=025",
    token: "GRT",
    emailDomain: "thegraph.com",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Decentraland DAO",
    iconURL: "https://cryptologos.cc/logos/decentraland-mana-logo.png?v=025",
    token: "MANA",
    emailDomain: "decentraland.org",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "PancakeSwap DAO",
    iconURL: "https://cryptologos.cc/logos/pancake-swap-cake-logo.png?v=025",
    token: "CAKE",
    emailDomain: "pancakeswap.finance",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "UMA DAO",
    iconURL: "https://cryptologos.cc/logos/uma-uma-logo.png?v=025",
    token: "UMA",
    emailDomain: "uma.xyz",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Gnosis DAO",
    iconURL: "https://cryptologos.cc/logos/gnosis-gno-logo.png?v=025",
    token: "GNO",
    emailDomain: "gnosis.io",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "1inch DAO",
    iconURL: "https://cryptologos.cc/logos/1inch-1inch-logo.png?v=025",
    token: "1INCH",
    emailDomain: "1inch.io",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
  {
    name: "Ocean DAO",
    iconURL: "https://cryptologos.cc/logos/ocean-protocol-ocean-logo.png?v=025",
    token: "OCEAN",
    emailDomain: "oceanprotocol.com",
    expectedDomain: "gmail.com",
    domainHash: keccak256(stringToBytes("gmail.com")),
  },
];
